version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: cimg/node:current
    
    working_directory: ~/tranquilpeak

    steps:
      - run: |
            if [[ "$CIRCLE_BRANCH" != "master" ]]; then
                circleci-agent step halt
            fi
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install --save

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run prod

      - run: git config --global user.email "nomaru@outlook.com"
      - run: git config --global user.name "noirgif(circleci)"
      - add_ssh_keys:
          fingerprints:
            - "d3:15:02:72:f5:16:05:4a:0a:dc:76:bc:2a:8d:4b:3e"

      - run:
            git add .
            git commit -C HEAD
            git rebase --autosquash
            git push
            cd ..
            git clone git@github.com:noirgif/blog
            rmdir blog/themes/tranquilpeak
            mv tranquilpeak blog/themes
            cd blog
            git commit -am "Update dependency"
            git push