version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:11.14.0-stretch
    
    working_directory: ~/blog

    steps:
      - run: |
            if [[ "$CIRCLE_BRANCH" != "master" ]]; then
                circleci-agent step halt
            fi
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install --save

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: git checkout -b build || git checkout build
      - run: npm run prod

      - run: git config --global user.email "nomaru@outlook.com"
      - run: git config --global user.name "noirgif(circleci)"
      - add_ssh_keys:
          fingerprints:
            - "d3:15:02:72:f5:16:05:4a:0a:dc:76:bc:2a:8d:4b:3e"
      
      - run: git commit -am "Build by circleci"
      - run: git push origin -f --set-upstream build

      - run: |
            cd ..
            git clone git@github.com:noirgif/blog
            cd blog
            git submodule foreach git pull origin build
            git commit -am "Update dependencies"
            git push
